title: Hakama
subtitle: "A fast, simple & powerful blog framework powered by Node.js."
description: "Hexo is a fast, simple & powerful blog framework powered by Node.js."
author: Kamil Warpechowski
language: en
timezone: UTC

url: https://blog.hakama.pl
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
category_dir: ""
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0
category_generator:
  per_page: 10
theme: navy
deploy:
  type: git
  repo: git@github.com:hexojs/hexojs.github.io.git

highlight:
  enable: true
  line_number: false

disqus_shortname: hexojs
google_analytics: UA-48498357-3
fb_admins: 100000247608790
github: kwarpechowski
